// Code generated by qtc from "tool_get_object_template.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line tool_get_object_template.qtpl:1
package codegen

//line tool_get_object_template.qtpl:1
import "github.com/grokify/mogo/text/stringcase"

//line tool_get_object_template.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line tool_get_object_template.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line tool_get_object_template.qtpl:2
func StreamToolGetObject(qw422016 *qt422016.Writer, obj stringcase.CaserNoun) {
//line tool_get_object_template.qtpl:2
	qw422016.N().S(`
package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/grokify/mogo/net/http/httpsimple"
	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/grokify/aha-mcp-server/mcputil"
)

type Get`)
//line tool_get_object_template.qtpl:19
	qw422016.E().S(obj.Singular.PascalCase())
//line tool_get_object_template.qtpl:19
	qw422016.N().S(`Params struct {
	`)
//line tool_get_object_template.qtpl:20
	qw422016.E().S(obj.Singular.PascalCase())
//line tool_get_object_template.qtpl:20
	qw422016.N().S(`ID string `)
//line tool_get_object_template.qtpl:20
	qw422016.N().S("`")
//line tool_get_object_template.qtpl:20
	qw422016.N().S(`json:"`)
//line tool_get_object_template.qtpl:20
	qw422016.E().S(obj.Singular.SnakeCase())
//line tool_get_object_template.qtpl:20
	qw422016.N().S(`_id" description:"`)
//line tool_get_object_template.qtpl:20
	qw422016.E().S(obj.Singular.Display())
//line tool_get_object_template.qtpl:20
	qw422016.N().S(` ID to get"`)
//line tool_get_object_template.qtpl:20
	qw422016.N().S("`")
//line tool_get_object_template.qtpl:20
	qw422016.N().S(`
}
	
func (tc *ToolsClient) Get`)
//line tool_get_object_template.qtpl:23
	qw422016.N().S(obj.Singular.PascalCase())
//line tool_get_object_template.qtpl:23
	qw422016.N().S(`(ctx context.Context, req *mcp.CallToolRequest, params Get`)
//line tool_get_object_template.qtpl:23
	qw422016.E().S(obj.Singular.PascalCase())
//line tool_get_object_template.qtpl:23
	qw422016.N().S(`Params) (*mcp.CallToolResult, any, error) {
	if resp, err := tc.simpleClient.Do(ctx, httpsimple.Request{
		Method: http.MethodGet,
		URL:    fmt.Sprintf("/api/v1/`)
//line tool_get_object_template.qtpl:26
	qw422016.N().S(obj.Plural.SnakeCase())
//line tool_get_object_template.qtpl:26
	qw422016.N().S(`/%s", params.`)
//line tool_get_object_template.qtpl:26
	qw422016.E().S(obj.Singular.PascalCase())
//line tool_get_object_template.qtpl:26
	qw422016.N().S(`ID),
	}); err != nil {
		return mcputil.NewCallToolResultForAny(fmt.Sprintf("error getting `)
//line tool_get_object_template.qtpl:28
	qw422016.E().S(obj.Singular.Display())
//line tool_get_object_template.qtpl:28
	qw422016.N().S(`: %v", err), true), nil, err
	} else if `)
//line tool_get_object_template.qtpl:29
	qw422016.E().S(obj.Singular.CamelCase())
//line tool_get_object_template.qtpl:29
	qw422016.N().S(`JSON, err := io.ReadAll(resp.Body); err != nil {
		return mcputil.NewCallToolResultForAny(fmt.Sprintf("Error reading API response: %v", err), true), nil, err
	} else if jsonData, err := json.Marshal(map[string]any{
		"`)
//line tool_get_object_template.qtpl:32
	qw422016.E().S(obj.Singular.SnakeCase())
//line tool_get_object_template.qtpl:32
	qw422016.N().S(`": json.RawMessage(`)
//line tool_get_object_template.qtpl:32
	qw422016.E().S(obj.Singular.CamelCase())
//line tool_get_object_template.qtpl:32
	qw422016.N().S(`JSON),
		"status_code": resp.StatusCode,
	}); err != nil {
		return mcputil.NewCallToolResultForAny(fmt.Sprintf("Error marshaling response: %v", err), true), nil, err
	} else {
		return mcputil.NewCallToolResultForAny(string(jsonData), false), nil, nil
	}
}

func Get`)
//line tool_get_object_template.qtpl:41
	qw422016.E().S(obj.Singular.PascalCase())
//line tool_get_object_template.qtpl:41
	qw422016.N().S(`Tool() *mcp.Tool {
	return &mcp.Tool{
		Name:        "get_`)
//line tool_get_object_template.qtpl:43
	qw422016.E().S(obj.Singular.SnakeCase())
//line tool_get_object_template.qtpl:43
	qw422016.N().S(`",
		Description: "Get `)
//line tool_get_object_template.qtpl:44
	qw422016.E().S(obj.Singular.Display())
//line tool_get_object_template.qtpl:44
	qw422016.N().S(` from Aha",
		InputSchema: &jsonschema.Schema{
			Type: "object",
			Properties: map[string]*jsonschema.Schema{
				"`)
//line tool_get_object_template.qtpl:48
	qw422016.E().S(obj.Singular.SnakeCase())
//line tool_get_object_template.qtpl:48
	qw422016.N().S(`_id": {
					Type:        "string",
					Description: "`)
//line tool_get_object_template.qtpl:50
	qw422016.E().S(obj.Singular.Display())
//line tool_get_object_template.qtpl:50
	qw422016.N().S(` ID to get",
				},
			},
			Required: []string{"`)
//line tool_get_object_template.qtpl:53
	qw422016.E().S(obj.Singular.SnakeCase())
//line tool_get_object_template.qtpl:53
	qw422016.N().S(`_id"},
		},
	}
}
`)
//line tool_get_object_template.qtpl:57
}

//line tool_get_object_template.qtpl:57
func WriteToolGetObject(qq422016 qtio422016.Writer, obj stringcase.CaserNoun) {
//line tool_get_object_template.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tool_get_object_template.qtpl:57
	StreamToolGetObject(qw422016, obj)
//line tool_get_object_template.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line tool_get_object_template.qtpl:57
}

//line tool_get_object_template.qtpl:57
func ToolGetObject(obj stringcase.CaserNoun) string {
//line tool_get_object_template.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line tool_get_object_template.qtpl:57
	WriteToolGetObject(qb422016, obj)
//line tool_get_object_template.qtpl:57
	qs422016 := string(qb422016.B)
//line tool_get_object_template.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line tool_get_object_template.qtpl:57
	return qs422016
//line tool_get_object_template.qtpl:57
}
